<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Project Updates Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px 10px 0 0;
            text-align: center;
        }
        .content {
            background: white;
            padding: 30px;
            border-radius: 0 0 10px 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .summary-card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }
        .summary-card h3 {
            margin: 0;
            font-size: 2em;
        }
        .summary-card h5 {
            margin: 5px 0;
            opacity: 0.9;
        }
        .employee-section {
            margin-bottom: 30px;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            overflow: hidden;
        }
        .employee-header {
            background: #f8f9fa;
            padding: 15px 20px;
            border-bottom: 1px solid #e9ecef;
        }
        .employee-details {
            padding: 20px;
        }
        .badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            font-weight: bold;
        }
        .badge-primary { background: #007bff; color: white; }
        .badge-info { background: #17a2b8; color: white; }
        .badge-warning { background: #ffc107; color: #212529; }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .table th, .table td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #e9ecef;
        }
        .table th {
            background: #f8f9fa;
            font-weight: 600;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e9ecef;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Employee Project Updates Report</h1>
        <p>Period: {{ $startDate->format('M d, Y') }} - {{ $endDate->format('M d, Y') }}</p>
        <p>Generated by: {{ $requestedBy->name }} ({{ $requestedBy->email }})</p>
        <p>Generated on: {{ now()->format('M d, Y H:i') }}</p>
    </div>

    <div class="content">
        @if(count($employeeReports) > 0)
            <!-- Summary Section -->
            <div class="summary-cards">
                <div class="summary-card">
                    <h3>{{ count($employeeReports) }}</h3>
                    <h5>Total Employees</h5>
                </div>
                <div class="summary-card">
                    <h3>{{ array_sum(array_column(array_column($employeeReports, 'total_updates'), 'total_updates')) }}</h3>
                    <h5>Total Updates</h5>
                </div>
                <div class="summary-card">
                    <h3>{{ array_sum(array_column(array_column($employeeReports, 'project_updates'), 'project_updates')) }}</h3>
                    <h5>Project Updates</h5>
                </div>
                <div class="summary-card">
                    <h3>{{ array_sum(array_column(array_column($employeeReports, 'invoice_updates'), 'invoice_updates')) }}</h3>
                    <h5>Invoice Updates</h5>
                </div>
            </div>

            <!-- Employee Details -->
            @foreach($employeeReports as $employeeReport)
                <div class="employee-section">
                    <div class="employee-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <div>
                                <strong>👤 {{ $employeeReport['employee']->name }}</strong>
                                <span style="color: #6c757d; margin-left: 10px;">({{ $employeeReport['employee']->department }})</span>
                            </div>
                            <div>
                                <span class="badge badge-primary">{{ $employeeReport['total_updates'] }} Total</span>
                                <span class="badge badge-info">{{ $employeeReport['project_updates'] }} Projects</span>
                                <span class="badge badge-warning">{{ $employeeReport['invoice_updates'] }} Invoices</span>
                            </div>
                        </div>
                    </div>
                    <div class="employee-details">
                        @if(count($employeeReport['updates']) > 0)
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Date & Time</th>
                                        <th>Type</th>
                                        <th>Reference</th>
                                        <th>Update Details</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($employeeReport['updates'] as $update)
                                        <tr>
                                            <td>{{ $update->update_date->format('d-m-Y H:i') }}</td>
                                            <td>
                                                @if($update->product_id)
                                                    <span class="badge badge-info">Project</span>
                                                @elseif($update->invoice_id)
                                                    <span class="badge badge-warning">Invoice</span>
                                                @endif
                                            </td>
                                            <td>
                                                @if($update->product_id && $update->product)
                                                    {{ $update->product->product_name_en }}
                                                @elseif($update->invoice_id && $update->invoice)
                                                    {{ $update->invoice->invoice_number }} - {{ $update->invoice->project_name }}
                                                @else
                                                    N/A
                                                @endif
                                            </td>
                                            <td>
                                                @if($update->request_text)
                                                    <div style="color: #6c757d;">
                                                        <small><strong>Request:</strong></small><br>
                                                        {!! nl2br(e($update->request_text)) !!}
                                                    </div>
                                                @else
                                                    @if($update->update_point_1)
                                                        <div>• {{ $update->update_point_1 }}</div>
                                                    @endif
                                                    @if($update->update_point_2)
                                                        <div>• {{ $update->update_point_2 }}</div>
                                                    @endif
                                                    @if($update->update_point_3)
                                                        @if(json_decode($update->update_point_3))
                                                            @foreach(json_decode($update->update_point_3) as $point)
                                                                <div>• {{ $point }}</div>
                                                            @endforeach
                                                        @else
                                                            <div>• {{ $update->update_point_3 }}</div>
                                                        @endif
                                                    @endif
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <p style="color: #6c757d; text-align: center; padding: 20px;">
                                No updates found for this employee in the selected period.
                            </p>
                        @endif
                    </div>
                </div>
            @endforeach
        @else
            <div style="text-align: center; padding: 50px;">
                <div style="font-size: 3em; color: #6c757d; margin-bottom: 20px;">📊</div>
                <h3 style="color: #6c757d;">No Updates Found</h3>
                <p style="color: #6c757d;">No project updates found for the selected criteria.</p>
            </div>
        @endif

        <div class="footer">
            <p><strong>Niranjan Enterprises</strong></p>
            <p>This is an automated report generated from the CRM system.</p>
            <p>If you have any questions, please contact the system administrator.</p>
        </div>
    </div>
</body>
</html>
